name:                "advent-of-code"
description:         "Advent of Code 2024 solutions by nekowinston"
version:             "0.1.0.0"
homepage:            "https://code.winston.sh/winston/advent-of-code-2024"
license:             "BSD-3-Clause"
author:              "nekowinston"
maintainer:          "hey@winston.sh"
copyright:           "2024 nekowinston"

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-missing-export-lists

library:
  source-dirs: src

executables:
  advent-of-code-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - advent-of-code
    - optparse-applicative >= 0.18 && < 1

tests:
  advent-of-code-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent-of-code
    - HUnit
