on:
  push:
    branches: ["main"]
    paths: ['**.hs', '**.lock']
  pull_request:
    branches: ["main"]
    paths: ['**.hs', '**.lock']

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: https://github.com/haskell-actions/setup@v2
      with:
        ghc-version: 9.8.2
        enable-stack: true
        stack-version: 3.1.1

    - name: Cache
      uses: actions/cache@v4
      env:
        cache-name: cache-stack
      with:
        path: .stack-work
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('stack.yaml.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Build
      run: stack build

    - name: Run tests
      run: stack test
