on:
  push:
    branches: ["main"]
    paths: ['**.hs', '**.lock']
  pull_request:
    branches: ["main"]
    paths: ['**.hs', '**.lock']

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: https://github.com/DeterminateSystems/nix-installer-action@v16
      with:
        diagnostic-endpoint: ""

    - uses: https://github.com/DeterminateSystems/magic-nix-cache-action@v8
      with:
        diagnostic-endpoint: ""

    - name: Build
      run: nix build
