on:
  push:
    branches: ["main"]
    paths:
    - '.forgejo/**'
    - '**.hs'
    - '**.lock'
  pull_request:
    branches: ["main"]
    paths: 
    - '.forgejo/**'
    - '**.hs'
    - '**.lock'

permissions:
  contents: read

env:
  NIX_CONFIG: |
    accept-flake-config = true
    extra-substituters = http://127.0.0.1:37515

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: https://github.com/DeterminateSystems/nix-installer-action@v16
      with:
        diagnostic-endpoint: ""

    - uses: https://github.com/DeterminateSystems/magic-nix-cache-action@v8
      with:
        diagnostic-endpoint: ""

    - name: Build
      run: nix build -Lv
